site:
  # each line is a partition (Paxos group), the first is the master site_name:port
  # the last column is the learner
  # - ["s101:8001", "s201:8101", "s301:8201", "s401:8301"]
  server:
    - ["s101:13501", "s201:13601", "s301:13701", "s401:13801"]
    - ["s102:13502", "s202:13602", "s302:13702", "s402:13802"]
    - ["s103:13503", "s203:13603", "s303:13703", "s403:13803"]
    - ["s104:13504", "s204:13604", "s304:13704", "s404:13804"]
    - ["s105:13505", "s205:13605", "s305:13705", "s405:13805"]
    - ["s106:13506", "s206:13606", "s306:13706", "s406:13806"]
    - ["s107:13507", "s207:13607", "s307:13707", "s407:13807"]
    - ["s108:13508", "s208:13608", "s308:13708", "s408:13808"]
    - ["s109:13509", "s209:13609", "s309:13709", "s409:13809"]
    - ["s110:13510", "s210:13610", "s310:13710", "s410:13810"]
    - ["s111:13511", "s211:13611", "s311:13711", "s411:13811"]
    - ["s112:13512", "s212:13612", "s312:13712", "s412:13812"]
    - ["s113:13513", "s213:13613", "s313:13713", "s413:13813"]

# s101: localhost
# s201: p1
# s301: p2
# s401: learner 
process:
  s101: localhost
  s201: p1
  s301: p2
  s401: learner
  s102: localhost
  s202: p1
  s302: p2
  s402: learner
  s103: localhost
  s203: p1
  s303: p2
  s403: learner
  s104: localhost
  s204: p1
  s304: p2
  s404: learner
  s105: localhost
  s205: p1
  s305: p2
  s405: learner
  s106: localhost
  s206: p1
  s306: p2
  s406: learner
  s107: localhost
  s207: p1
  s307: p2
  s407: learner
  s108: localhost
  s208: p1
  s308: p2
  s408: learner
  s109: localhost
  s209: p1
  s309: p2
  s409: learner
  s110: localhost
  s210: p1
  s310: p2
  s410: learner
  s111: localhost
  s211: p1
  s311: p2
  s411: learner
  s112: localhost
  s212: p1
  s312: p2
  s412: learner
  s113: localhost
  s213: p1
  s313: p2
  s413: learner

# process_name - host_addr map
host:
  localhost: 127.0.0.1
  p1: 127.0.0.1
  p2: 127.0.0.1
  learner: 127.0.0.1