site:
  # each line is a partition (Paxos group), the first is the master site_name:port
  # the last column is the learner
  # - ["s101:8001", "s201:8101", "s301:8201", "s401:8301"]
  server:
    - ["s101:12501", "s201:12601", "s301:12701", "s401:12801"]
    - ["s102:12502", "s202:12602", "s302:12702", "s402:12802"]
    - ["s103:12503", "s203:12603", "s303:12703", "s403:12803"]
    - ["s104:12504", "s204:12604", "s304:12704", "s404:12804"]
    - ["s105:12505", "s205:12605", "s305:12705", "s405:12805"]
    - ["s106:12506", "s206:12606", "s306:12706", "s406:12806"]
    - ["s107:12507", "s207:12607", "s307:12707", "s407:12807"]
    - ["s108:12508", "s208:12608", "s308:12708", "s408:12808"]
    - ["s109:12509", "s209:12609", "s309:12709", "s409:12809"]
    - ["s110:12510", "s210:12610", "s310:12710", "s410:12810"]
    - ["s111:12511", "s211:12611", "s311:12711", "s411:12811"]
    - ["s112:12512", "s212:12612", "s312:12712", "s412:12812"]
    - ["s113:12513", "s213:12613", "s313:12713", "s413:12813"]
    - ["s114:12514", "s214:12614", "s314:12714", "s414:12814"]
    - ["s115:12515", "s215:12615", "s315:12715", "s415:12815"]
    - ["s116:12516", "s216:12616", "s316:12716", "s416:12816"]
    - ["s117:12517", "s217:12617", "s317:12717", "s417:12817"]
    - ["s118:12518", "s218:12618", "s318:12718", "s418:12818"]
    - ["s119:12519", "s219:12619", "s319:12719", "s419:12819"]
    - ["s120:12520", "s220:12620", "s320:12720", "s420:12820"]
    - ["s121:12521", "s221:12621", "s321:12721", "s421:12821"]
    - ["s122:12522", "s222:12622", "s322:12722", "s422:12822"]
    - ["s123:12523", "s223:12623", "s323:12723", "s423:12823"]
    - ["s124:12524", "s224:12624", "s324:12724", "s424:12824"]
    - ["s125:12525", "s225:12625", "s325:12725", "s425:12825"]
    - ["s126:12526", "s226:12626", "s326:12726", "s426:12826"]
    - ["s127:12527", "s227:12627", "s327:12727", "s427:12827"]
    - ["s128:12528", "s228:12628", "s328:12728", "s428:12828"]
    - ["s129:12529", "s229:12629", "s329:12729", "s429:12829"]
    - ["s130:12530", "s230:12630", "s330:12730", "s430:12830"]

# s101: localhost
# s201: p1
# s301: p2
# s401: learner 
process:
  s101: localhost
  s201: p1
  s301: p2
  s401: learner
  s102: localhost
  s202: p1
  s302: p2
  s402: learner
  s103: localhost
  s203: p1
  s303: p2
  s403: learner
  s104: localhost
  s204: p1
  s304: p2
  s404: learner
  s105: localhost
  s205: p1
  s305: p2
  s405: learner
  s106: localhost
  s206: p1
  s306: p2
  s406: learner
  s107: localhost
  s207: p1
  s307: p2
  s407: learner
  s108: localhost
  s208: p1
  s308: p2
  s408: learner
  s109: localhost
  s209: p1
  s309: p2
  s409: learner
  s110: localhost
  s210: p1
  s310: p2
  s410: learner
  s111: localhost
  s211: p1
  s311: p2
  s411: learner
  s112: localhost
  s212: p1
  s312: p2
  s412: learner
  s113: localhost
  s213: p1
  s313: p2
  s413: learner
  s114: localhost
  s214: p1
  s314: p2
  s414: learner
  s115: localhost
  s215: p1
  s315: p2
  s415: learner
  s116: localhost
  s216: p1
  s316: p2
  s416: learner
  s117: localhost
  s217: p1
  s317: p2
  s417: learner
  s118: localhost
  s218: p1
  s318: p2
  s418: learner
  s119: localhost
  s219: p1
  s319: p2
  s419: learner
  s120: localhost
  s220: p1
  s320: p2
  s420: learner
  s121: localhost
  s221: p1
  s321: p2
  s421: learner
  s122: localhost
  s222: p1
  s322: p2
  s422: learner
  s123: localhost
  s223: p1
  s323: p2
  s423: learner
  s124: localhost
  s224: p1
  s324: p2
  s424: learner
  s125: localhost
  s225: p1
  s325: p2
  s425: learner
  s126: localhost
  s226: p1
  s326: p2
  s426: learner
  s127: localhost
  s227: p1
  s327: p2
  s427: learner
  s128: localhost
  s228: p1
  s328: p2
  s428: learner
  s129: localhost
  s229: p1
  s329: p2
  s429: learner
  s130: localhost
  s230: p1
  s330: p2
  s430: learner

# process_name - host_addr map
host:
  localhost: 127.0.0.1
  p1: 127.0.0.1
  p2: 127.0.0.1
  learner: 127.0.0.1