site:
  # each line is a partition (Paxos group), the first is the master site_name:port
  # the last column is the learner
  # - ["s101:8001", "s201:8101", "s301:8201", "s401:8301"]
  server:
    - ["s101:13501", "s201:13601", "s301:13701", "s401:13801"]
    - ["s102:13502", "s202:13602", "s302:13702", "s402:13802"]
    - ["s103:13503", "s203:13603", "s303:13703", "s403:13803"]

# s101: localhost
# s201: p1
# s301: p2
# s401: learner 
process:
  s101: localhost
  s201: p1
  s301: p2
  s401: learner
  s102: localhost
  s202: p1
  s302: p2
  s402: learner
  s103: localhost
  s203: p1
  s303: p2
  s403: learner

# process_name - host_addr map
host:
  localhost: 127.0.0.1
  p1: 127.0.0.1
  p2: 127.0.0.1
  learner: 127.0.0.1